---
-   name: Update apt-cache and upgrade
    apt:
        force_apt_get: yes
        update_cache: "True"
        cache_valid_time: 3600
        upgrade: yes

-   name: Create databaseServer container
    docker_container:
        name: databaseServer
        image: mysql:5.7
        state: started
        ports:
          - "3306:3306"
        volumes:
          - mysqlD:/var/lib/mysql
        restart: yes
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_pass }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_PASSWORD: "{{ mysql_root_pass }}"
