name: Docker configuration

on:
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed

jobs:

  build:
    name: Building docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for docker
        uses: actions/checkout@v2
      - name: publish docker image
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile_prod
          tags: ${{ secrets.DOCKER_USERNAME }}/microblog:latest
          push: true
